import { useEffect, useMemo, useState } from 'react';
import { Check, CheckCircle2, Edit3, ExternalLink, Plus, Search, Trash2, Wrench } from 'lucide-react';
import { Modal } from '../../components/Modal';
import { ManagementSidebar } from '../management/ManagementSidebar';
import { loadManagedSkills } from '../skills/skill.storage';
import { loadGlobalTools, persistGlobalTools } from './tool.storage';
import type { GlobalTool, ToolField, ToolFieldType, ToolMethod } from './tool.types';

const fieldTypes: ToolFieldType[] = ['string', 'number', 'boolean', 'object', 'array'];
const methodLabels: Record<ToolMethod, string> = { GET: 'GET', POST: 'POST', PUT: 'PUT', DELETE: 'DELETE' };
const newField = (prefix: string, index: number): ToolField => ({ id: `${prefix}-${Date.now()}-${index}`, name: '', type: 'string', required: true });

function blankTool(): GlobalTool { return { id: `tool-${Date.now()}`, name: '', key: '', description: '', method: 'POST', endpoint: '', enabled: true, inputFields: [newField('input', 0)], outputFields: [newField('output', 0)], updatedAt: '刚刚' }; }

function FieldEditor({ title, fields, update }: { title: string; fields: ToolField[]; update: (fields: ToolField[]) => void }) {
  const patch = (id: string, value: Partial<ToolField>) => update(fields.map(field => field.id === id ? { ...field, ...value } : field));
  return <section className="tool-fields"><header><strong>{title}</strong><button className="text-button" onClick={() => update([...fields, newField(title === '输入参数' ? 'input' : 'output', fields.length)])}><Plus size={14} />添加参数</button></header>{fields.length ? fields.map(field => <div className="tool-field-row" key={field.id}><input aria-label={`${title}参数名`} placeholder="参数名" value={field.name} onChange={event => patch(field.id, { name: event.target.value })} /><select aria-label={`${title}参数类型`} value={field.type} onChange={event => patch(field.id, { type: event.target.value as ToolFieldType })}>{fieldTypes.map(type => <option key={type}>{type}</option>)}</select>{title === '输入参数' ? <label className="field-check"><input type="checkbox" checked={field.required} onChange={event => patch(field.id, { required: event.target.checked })} />必填</label> : null}<button className="icon-button" aria-label={`删除${title}参数`} onClick={() => update(fields.filter(item => item.id !== field.id))}><Trash2 size={15} /></button></div>) : <div className="tool-fields-empty">暂无参数</div>}</section>;
}

function ToolEditor({ initial, close, save }: { initial: GlobalTool; close: () => void; save: (tool: GlobalTool) => void }) {
  const [draft, setDraft] = useState(structuredClone(initial));
  const patch = (value: Partial<GlobalTool>) => setDraft(current => ({ ...current, ...value }));
  return <Modal title={initial.name ? '编辑工具' : '新建工具'} wide onClose={close} footer={<><button className="secondary-button" onClick={close}>取消</button><button className="primary-button" onClick={() => save({ ...draft, name: draft.name.trim() || '未命名工具', key: draft.key.trim() || `tool.${Date.now()}`, updatedAt: '刚刚' })}><Check size={15} />保存工具</button></>}><div className="tool-editor"><div className="tool-basic-grid"><label>工具名称<input aria-label="工具名称" value={draft.name} onChange={event => patch({ name: event.target.value })} placeholder="例如：查询订单状态" /></label><label>工具标识<input aria-label="工具标识" value={draft.key} onChange={event => patch({ key: event.target.value })} placeholder="例如：order.query" /></label><label>请求方式<select aria-label="请求方式" value={draft.method} onChange={event => patch({ method: event.target.value as ToolMethod })}>{Object.keys(methodLabels).map(method => <option key={method}>{method}</option>)}</select></label><label className="tool-endpoint">接口地址<input aria-label="接口地址" value={draft.endpoint} onChange={event => patch({ endpoint: event.target.value })} placeholder="https://api.example.com/orders/{order_id}" /></label></div><label className="tool-description">描述<textarea aria-label="工具描述" value={draft.description} onChange={event => patch({ description: event.target.value })} placeholder="说明工具什么时候使用" /></label><div className="tool-switch-row"><span>可用状态</span><button className={`switch ${draft.enabled ? 'on' : ''}`} role="switch" aria-checked={draft.enabled} onClick={() => patch({ enabled: !draft.enabled })}><i /></button><strong>{draft.enabled ? '启用' : '停用'}</strong></div><FieldEditor title="输入参数" fields={draft.inputFields} update={inputFields => patch({ inputFields })} /><FieldEditor title="输出参数" fields={draft.outputFields} update={outputFields => patch({ outputFields })} /></div></Modal>;
}

export function ToolManagementPage({ onOpenApps, onOpenSkills, onOpenCards }: { onOpenApps: () => void; onOpenSkills: () => void; onOpenCards: () => void }) {
  const [tools, setTools] = useState(loadGlobalTools); const [search, setSearch] = useState(''); const [editor, setEditor] = useState<GlobalTool | null>(null); const [toast, setToast] = useState(''); const [tested, setTested] = useState<string | null>(null);
  useEffect(() => persistGlobalTools(tools), [tools]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 1800); return () => clearTimeout(timer); }, [toast]);
  const visible = useMemo(() => tools.filter(tool => `${tool.name} ${tool.key} ${tool.endpoint}`.toLowerCase().includes(search.toLowerCase())), [tools, search]);
  const save = (tool: GlobalTool) => { setTools(current => current.some(item => item.id === tool.id) ? current.map(item => item.id === tool.id ? tool : item) : [tool, ...current]); setEditor(null); setToast('工具已保存'); };
  const test = (tool: GlobalTool) => { setTested(tool.id); setToast(`${tool.name} 测试请求已发送`); setTimeout(() => setTested(null), 1400); };
  const remove = (tool: GlobalTool) => { if (loadManagedSkills().some(skill => (skill.toolBindings ?? []).some(binding => binding.toolId === tool.id))) { setToast('该工具已被 Skill 引用，无法删除'); return; } setTools(current => current.filter(item => item.id !== tool.id)); setToast('工具已删除'); };
  return <div className="management-body"><ManagementSidebar active="工具" onOpenApps={onOpenApps} onOpenSkills={onOpenSkills} onOpenTools={() => undefined} onOpenCards={onOpenCards} /><main className="tools-main"><header className="tools-page-header"><div><h1>工具</h1><p>{tools.length} 个全局工具</p></div><button className="primary-button" onClick={() => setEditor(blankTool())}><Plus size={15} />新建工具</button></header><div className="tools-toolbar"><label className="search-field"><Search size={16} /><input aria-label="搜索工具" value={search} onChange={event => setSearch(event.target.value)} placeholder="搜索工具名称、标识或接口地址" /></label><span>{visible.length} 个结果</span></div><div className="tools-table"><div className="tools-row tools-row-head"><span>工具</span><span>请求</span><span>参数</span><span>状态</span><span>更新</span><span>操作</span></div>{visible.map(tool => <div className="tools-row" key={tool.id}><div className="tool-name-cell"><i><Wrench size={17} /></i><span><strong>{tool.name}</strong><small>{tool.key}</small></span></div><span><b className={`method method-${tool.method.toLowerCase()}`}>{tool.method}</b><small className="endpoint-text">{tool.endpoint || '未设置接口地址'}</small></span><span>{tool.inputFields.length} 入参 · {tool.outputFields.length} 出参</span><span><button className={`status-toggle ${tool.enabled ? 'enabled' : ''}`} onClick={() => setTools(current => current.map(item => item.id === tool.id ? { ...item, enabled: !item.enabled } : item))}><i />{tool.enabled ? '启用' : '停用'}</button></span><span>{tool.updatedAt}</span><span className="tool-actions"><button className="icon-button" aria-label={`测试工具 ${tool.name}`} onClick={() => test(tool)}>{tested === tool.id ? <CheckCircle2 size={16} /> : <ExternalLink size={16} />}</button><button className="icon-button" aria-label={`编辑工具 ${tool.name}`} onClick={() => setEditor(tool)}><Edit3 size={16} /></button><button className="icon-button danger" aria-label={`删除工具 ${tool.name}`} onClick={() => remove(tool)}><Trash2 size={16} /></button></span></div>)}{!visible.length ? <div className="tools-empty">没有找到工具</div> : null}</div></main>{editor ? <ToolEditor initial={editor} close={() => setEditor(null)} save={save} /> : null}{toast ? <div className="toast" role="status">{toast}</div> : null}</div>;
}
